.TH "src/lexer/CMakeLists.txt" 3 "2020年 六月 11日 星期四" "cxescore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lexer/CMakeLists.txt
.SH SYNOPSIS
.br
.PP
.SS "函数"

.in +1c
.ti -1c
.RI "\fBcmake_minimum_required\fP (VERSION 3\&.8) aux_source_directory(\&. DIR_CXESCORE_LEXER_SRCS) add_library(lexer $"
.br
.in -1c
.SH "函数说明"
.PP 
.SS "cmake_minimum_required (VERSION 3\&. 8)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 cxescore 的 源代码自动生成\&.
