.TH "src/lexer/lexer.hpp" 3 "2020年 六月 11日 星期四" "cxescore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lexer/lexer.hpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include\&.hpp'\fP
.br

.SS "命名空间"

.in +1c
.ti -1c
.RI " \fBcxesCore\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "vector< string > \fBcxesCore::lexer\fP (istream &input)"
.br
.RI "lexer "
.in -1c
.SH "作者"
.PP 
由 Doyxgen 通过分析 cxescore 的 源代码自动生成\&.
