.TH "src/helpers/stringHelper.cpp" 3 "2020年 六月 11日 星期四" "cxescore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/helpers/stringHelper.cpp
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./include\&.hpp'\fP
.br
\fC#include 'stringHelper\&.hpp'\fP
.br

.SS "函数"

.in +1c
.ti -1c
.RI "vector< string > \fBsplit\fP (const string &str, const string &pattern)"
.br
.ti -1c
.RI "\fBisdigit_s_t\fP \fBisdigit_s\fP (const string str)"
.br
.in -1c
.SH "函数说明"
.PP 
.SS "\fBisdigit_s_t\fP isdigit_s (const string str)"

.SS "vector<string> split (const string & str, const string & pattern)"

.SH "作者"
.PP 
由 Doyxgen 通过分析 cxescore 的 源代码自动生成\&.
