.TH "src/config.h" 3 "2020年 六月 11日 星期四" "cxescore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/config.h
.SH SYNOPSIS
.br
.PP
.SS "变量"

.in +1c
.ti -1c
.RI "static const char * \fBcxescoreVersion\fP ='1\&.0\&.5'"
.br
.ti -1c
.RI "static const char * \fBcxescoreBuildTime\fP ='20200610\-194155'"
.br
.in -1c
.SH "变量说明"
.PP 
.SS "const char* cxescoreBuildTime ='20200610\-194155'\fC [static]\fP"

.SS "const char* cxescoreVersion ='1\&.0\&.5'\fC [static]\fP"

.SH "作者"
.PP 
由 Doyxgen 通过分析 cxescore 的 源代码自动生成\&.
