.TH "src/console.h" 3 "2020年 六月 11日 星期四" "cxescore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/console.h
.SH SYNOPSIS
.br
.PP
.SS "变量"

.in +1c
.ti -1c
.RI "const auto \fBRESET\fP = '\\033[0m'"
.br
.ti -1c
.RI "const auto \fBBLACK\fP = '\\033[30m'"
.br
.ti -1c
.RI "const auto \fBRED\fP = '\\033[31m'"
.br
.ti -1c
.RI "const auto \fBGREEN\fP = '\\033[32m'"
.br
.ti -1c
.RI "const auto \fBYELLOW\fP = '\\033[33m'"
.br
.ti -1c
.RI "const auto \fBBLUE\fP = '\\033[34m'"
.br
.ti -1c
.RI "const auto \fBMAGENTA\fP = '\\033[35m'"
.br
.ti -1c
.RI "const auto \fBCYAN\fP = '\\033[36m'"
.br
.ti -1c
.RI "const auto \fBWHITE\fP = '\\033[37m'"
.br
.ti -1c
.RI "const auto \fBLIGHTBLACK\fP = '\\033[1m\\033[30m'"
.br
.ti -1c
.RI "const auto \fBLIGHTRED\fP = '\\033[1m\\033[31m'"
.br
.ti -1c
.RI "const auto \fBLIGHTGREEN\fP = '\\033[1m\\033[32m'"
.br
.ti -1c
.RI "const auto \fBLIGHTYELLOW\fP = '\\033[1m\\033[33m'"
.br
.ti -1c
.RI "const auto \fBLIGHTBLUE\fP = '\\033[1m\\033[34m'"
.br
.ti -1c
.RI "const auto \fBLIGHTMAGENTA\fP = '\\033[1m\\033[35m'"
.br
.ti -1c
.RI "const auto \fBLIGHTCYAN\fP = '\\033[1m\\033[36m'"
.br
.ti -1c
.RI "const auto \fBLIGHTWHITE\fP = '\\033[1m\\033[37m'"
.br
.ti -1c
.RI "const auto \fBCLEAN\fP = '\\033[2J'"
.br
.in -1c
.SH "变量说明"
.PP 
.SS "const auto BLACK = '\\033[30m'"

.SS "const auto BLUE = '\\033[34m'"

.SS "const auto CLEAN = '\\033[2J'"

.SS "const auto CYAN = '\\033[36m'"

.SS "const auto GREEN = '\\033[32m'"

.SS "const auto LIGHTBLACK = '\\033[1m\\033[30m'"

.SS "const auto LIGHTBLUE = '\\033[1m\\033[34m'"

.SS "const auto LIGHTCYAN = '\\033[1m\\033[36m'"

.SS "const auto LIGHTGREEN = '\\033[1m\\033[32m'"

.SS "const auto LIGHTMAGENTA = '\\033[1m\\033[35m'"

.SS "const auto LIGHTRED = '\\033[1m\\033[31m'"

.SS "const auto LIGHTWHITE = '\\033[1m\\033[37m'"

.SS "const auto LIGHTYELLOW = '\\033[1m\\033[33m'"

.SS "const auto MAGENTA = '\\033[35m'"

.SS "const auto RED = '\\033[31m'"

.SS "const auto RESET = '\\033[0m'"

.SS "const auto WHITE = '\\033[37m'"

.SS "const auto YELLOW = '\\033[33m'"

.SH "作者"
.PP 
由 Doyxgen 通过分析 cxescore 的 源代码自动生成\&.
