.TH "cxesCore" 3 "2020年 六月 11日 星期四" "cxescore" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cxesCore
.SH SYNOPSIS
.br
.PP
.SS "类"

.in +1c
.ti -1c
.RI "class \fBVM\fP"
.br
.in -1c
.SS "函数"

.in +1c
.ti -1c
.RI "vector< string > \fBlexer\fP (istream &input)"
.br
.RI "lexer "
.in -1c
.SH "函数说明"
.PP 
.SS "vector< string > cxesCore::lexer (istream & input)"

.PP
lexer 
.SH "作者"
.PP 
由 Doyxgen 通过分析 cxescore 的 源代码自动生成\&.
